### ISSUE TITLE
请求

### ISSUE THREAD

**Issue by weilingyu2001** [Chen-yuiyui/NUAA-PA-ics2017#1]
学长你好我这部分有一些问题，可以麻烦学长发一下你的实验报告给我嘛，谢谢！

**Comment by Chen-yuiyui** [comment]
加我一个qq吧，514818129。或者你说一下你需要哪部分的报告。

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："weilingyu2001 ***@***.***&gt;;
发送时间：2021年5月13日(星期四) 晚上8:06
收件人："Chen-yuiyui/NUAA-PA-ics2017" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[Chen-yuiyui/NUAA-PA-ics2017] 请求 (#1)
-----------------------------------

 

 
学长你好我这部分有一些问题，可以麻烦学长发一下你的实验报告给我嘛，谢谢！
